### ISSUE TITLE
Bootstrap

### ISSUE THREAD

**Issue by Cyclic3** [RevisionHub/HTML#1]
Are we going top use bootstrap in conjunction with our own CSS, @HungJ24 ?

If so, @SnickersAdam might need to know, so that he can adjust his css, so that it doesn't cause problems.

**Comment by HungJ24** [comment]
late reply sorry, i was thinking bootstrap would be a better option for the project since we can all work in one framework. so everything works together. Adam might have to adjust some of his css but hopefully it won't be too much to change.

**Comment by HungJ24** [comment]
what has he written so far?

**Comment by Cyclic3** [comment]
_Decided on bootstrap use_
