### ISSUE TITLE
External fonts

### ISSUE THREAD

**Issue by Cyclic3** [RevisionHub/HTML#2]
HTTPS does not like external items. Would it be possible for you to do the following:
1. Turn all http://example.com/resource into /resources/resource
2. Remove all external fonts
3. Turn all of the file links into links for the webpage `file:///C:/Users/victor/Desktop/WelcomePage/page` to `/page`

I am really sorry, because the fonts looked so good!

**Comment by HungJ24** [comment]
done No. 1 & 3 but not sure i can remove all of the fonts, ive tried looking at embedding the fonts into css files but thats not working out great for me. any way you can work around the https font issue?
